<?php

namespace AppBundle\Repository\Statistic;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceRepository extends \Doctrine\ORM\EntityRepository
{

}
