<?php

namespace AppBundle\Repository\Statistic;

/**
 * DelayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelayRepository extends \Doctrine\ORM\EntityRepository
{

}
